# Generated by Django 3.2.16 on 2023-10-23 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_set_managed_to_true'),
        ('core', '0023_alter_jsonext_column_in_tblOfficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpimmIDGenerator',
            fields=[
                ('uuid', models.UUIDField(db_column='UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('next_insuree_id', models.IntegerField(db_column='NextInsuree')),
                ('next_claim_id', models.IntegerField(db_column='NextClaim')),
                ('current_year', models.SmallIntegerField(db_column='Year')),
                ('hf', models.ForeignKey(db_column='HF', on_delete=django.db.models.deletion.CASCADE, to='location.healthfacility')),
            ],
            options={
                'db_table': 'tblSpimmIDGenerator',
                'managed': True,
            },
        ),
    ]
