# Generated by Django 3.2.21 on 2023-09-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0020_paymentserviceprovider_has_login'),
        ('core', '0025_mutationlog_json_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='psp_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_payment.paymentserviceprovider'),
        ),
    ]
