# Generated by Django 3.2.21 on 2023-09-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_psp_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='psp_admin',
        ),
    ]
